### PR TITLE
AddingPowerSupport_CI/

### PR DESCRIPTION
**Pull request by santosh653**
Adding power support.,
Updating go versions to >=1.13 as lower versions are not supported.,

### CODE REVIEW

**Comment by santosh653** [comment]
Adding Power & Updating the go versions to 1.13/1.14/1.15 as lower versions are not supported.

Adding power support ppc64le with Continues Integration/testing so that code remains architecture independent.

This is part of the Ubuntu distribution for ppc64le. This helps us simplify testing later when distributions are re-building and re-releasing. For more info tag @gerrith3.

The build is successful on both arch: amd64/ppc64le, please find the Travis Link below.
https://travis-ci.com/github/santosh653/purell

Please let me know if you need any further details.,

Thank You !!

**Comment by mna** [comment]
@gerrith3 same comment as https://github.com/PuerkitoBio/goquery/pull/364#issuecomment-740248546

**Comment by gerrith3** [comment]
@mna answered it over there, feel free to reach out if you have other questions.  But @santosh653 should configure them any way you want them - we'd recommend sticking with a smaller set of modern go versions on ppc64le, but you can have him select more or all of the versions for amd64 as you desire.

**Comment by mna** [comment]
Yeah let's not arbitrarily drop support for any old version on amd64, at least as long as travis or other CI let's us do so. Feel free to use just the versions you need on ppc. Would be nice to add the missing recent versions on amd64 though.

**Comment by gerrith3** [comment]
@mna makes sense.  @santosh653 is in India, so he'll probably address this during our evening tonight.  For both of these.  ;)

**Comment by santosh653** [comment]
@mna I have retained the old go versions on amd64 accordingly changed the code, also added the support for power using only the supported Go versions.

I hope this change answers & addresses your query., Looping @gerrith3 
The Travis Build is successful with newly changed code.

Thank you !!

**Pull request merged**
