### PR TITLE
support the IDNA domains, make some of jehiah's tests pass 

### PR DESCRIPTION
**Pull request by zenovich**
(should be used together with the patched urlesc (see PR for urlesc as well))

### CODE REVIEW

**Comment by PuerkitoBio** [comment]
Hello Dmitry,

Thanks for taking a shot at that long-standing TODO! I don't know much about IDNA domains and how it should work, but instinctively, I feel like the tests are backwards - shouldn't the normalization take a Unicode domain and normalize it to ASCII format of IDNA?

Also, should the unicode format be normalized first (https://blog.golang.org/normalization)? Does that matter for IDNA domains, or are two different-but-canonically-identical Unicode domains treated as 2 separate domains?

If you know how that works or are willing to dig into this a bit more and can point me to relevant docs, I'd appreciate it. I'd love to get that merged and tick that todo box :)

Thanks,
Martin

**Comment by PuerkitoBio** [comment]
Looks like this unicode-canonicalization is handled by the "nameprep" process of IDNA: https://en.wikipedia.org/wiki/Nameprep

However, the golang.org/x/net/idna package does not seem to do that canonicalization part, while the userspace github.com/DanielOaks/go-idn does: https://play.golang.org/p/zS-UR4WhIx (can't run it in the playground, though).

I'd prefer a dep on a golang.org/x package, especially since the userspace one has that big warning about not being ready, maybe the nameprep/stringprep part is implemented elsewhere, or we need to do it by hand via the go.text/unicode/norm package (which is a shame, I'd expect the idna package to do the whole algorithm, not just part of it, but again, I know very little about IDNA).

**Comment by PuerkitoBio** [comment]
This PR should probably wait for this Go issue to be resolved, to see how the stdlib handles (or not) IDNA: https://github.com/golang/go/issues/13835

**Comment by zenovich** [comment]
Hello Martin,
  
First of all, I think that the unicode characters are much better for the normalized form since they are readable. I prefer to use them instead of ASCII.

Talking about the unicode normalization, although Nameprep is something from obsolete RFCs (https://tools.ietf.org/html/rfc3491 is obsoleted by https://tools.ietf.org/html/rfc5891), we have to ensure that our unicode is in NFC format and in lowercase to disambiguate. I think we should not bother about prohibited characters because the URL that contains them is incorrect (https://tools.ietf.org/html/rfc5894#section-4.1).

I found that we can normalize unicode strings using https://godoc.org/golang.org/x/text/secure/precis

**Comment by zenovich** [comment]
It would be great if we could add support for IDNA into Purell right now and not wait until February 2017.

**Comment by zenovich** [comment]
Btw, I see that current IDNA implementation already does folding to lowercase.

**Comment by PuerkitoBio** [comment]
Thanks a lot for your input and links. Good to know that x/net/idna implements the latest on IDNA and that stringprep/nameprep is obsoleted. The PRECIS normalization seems to be just what we need, indeed.

> First of all, I think that the unicode characters are much better for the normalized form since they are readable. I prefer to use them instead of ASCII.

That's my only (remaining) concern right now and the reason why I mentioned the pending Go issue. Purell is not about readability, but about normalization, and right now it seems the Go stdlib doesn't support a Unicode IDN, so if we use the Unicode format (even if it's normalized to NFC), the result of applying purell to an URL is a URL that you cannot fetch using the http client.

Normalizing to ascii (after having normalized the Unicode format using NFC) would be guaranteed to be usable as long as the URL is valid.

**Comment by PuerkitoBio** [comment]
In fact, I think that regardless of what the stdlib ends up doing with IDNA, purell should normalize to ascii. When you think about it, the unicode version is not even a valid URL, it's just a UI thing for end users. I'd like to hear arguments, if there are any, for Unicode (besides readability).

And we should probably handle the case where the URL is already in punycode, but not for an NFC-normalized domain. So we should decode to Unicode, normalize, and re-encode in this case (unless the NFC is not a hard requirement of the spec? it seems to be but I just took a quick look).

**Comment by zenovich** [comment]
I have no arguments for Unicode besides readability. I think that normalizing to ASCII is good and solves the problem very well.

**Comment by zenovich** [comment]
According to the https://tools.ietf.org/html/rfc5891#section-4.1 "By the time a string enters the IDNA registration process as  described in this specification, it MUST be in Unicode and in Normalization Form C". That's why there is no need in Unicode-normalization of the names converted from Punycode.

**Comment by zenovich** [comment]
@PuerkitoBio thanks

**Comment by zenovich** [comment]
@PuerkitoBio I think we can remove a line with 'mv' from '.travis.yml' now

**Pull request merged**
